name: Main command validation

on:
  push:
    branches: [*]
  pull_request:
    branches: [main]

jobs:
  build-linux:
      name: Validate BGCFlow wrapper in Linux
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: "3.8.x"
        - name: Install dependencies
          run: |
            $CONDA/bin/conda env update --file env.yaml --name base
        - name: Clone test
          run: |
            bgcflow clone bgcflow_test
          shell: bash
        - name: Init test
          run: |
            (cd bgcflow_test && bgcflow init)
          shell: bash
        - name: Rules test
          run: |
            (cd bgcflow_test && bgcflow rules)
          shell: bash
        - name: Run test
          run: |
            (cd bgcflow_test && bgcflow run -n)
          shell: bash
